name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"

      - name: Install dependencies
        run: npm ci

      - name: Lint and type check
        run: npm run lint

      - name: Lint SVGs
        run: npm run lint:svg

      - name: Build core package
        run: npm run build

      - name: Install package dependencies
        run: npm run install:packages

      - name: Build all packages with clean builds
        run: npm run build:packages:clean

      - name: Test examples
        run: npm run test:examples
